site/blog/urls.py
from django.conf.urls import url
from blog.views import *


urlpatterns = [
    url(r'^$', PostLV.as_view(), name='index'),
    url(r'^post/$', PostLV.as_view(), name='post_list'),
    url(r'^post/(?P<slug>[-\w]+)/$', PostDV.as_view(), name='post_detail'),
    url(r'^archive/$', PostAV.as_view(), name='post_archive'),
    url(r'^(?P<year>\d{4})/$', PostYAV.as_view(), name='post_year_archive'),
    url(r'^(?P<year>\d{4})/(?P<month>[a-z]{3})/$', PostMAV.as_view(), name='post_month_archive'),
    url(r'^(?P<year>\d{4})/(?P<month>[a-z]{3})/(?P<day>\d{1,2})/$', PostDAV.as_view(), name='post_day_archive'),
    url(r'^today/$', PostTAV.as_view(), name='post_today_archive'),

]

site/mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

from mysite.views import HomeView
urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^photo/', include('photo.urls', namespace='photo')),
    ]+static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

site/photo/urls.py
from django.conf.urls import url
from photo.views import *

urlpatterns = [
url(r'^$', AlbumLV.as_view(), name='index'),
url(r'^album/$', AlbumLV.as_view(), name='album_list'),
url(r'^album/(?P<pk>\d+)/$', AlbumDV.as_view(), name='album_detail'),
url(r'^photo/(?P<pk>\d+)/$', PhotoDV.as_view(), name='photo_detail'),
]

site/blog/models.py
from __future__ import unicode_literals
from django.utils.encoding import python_2_unicode_compatible

from django.db import models
from django.core.urlresolvers import reverse

@python_2_unicode_compatible
class Post(models.Model):
    title = models.CharField('TITLE', max_length=50)
    slug = models.SlugField('SLUG', unique = True, allow_unicode=True, help_text='one word for title alias.')
    description = models.CharField('DESCRIPTION', max_length=100, blank=True, help_text='simple description text.')
    content = models.TextField('CONTENT')
    create_date = models.DateTimeField('Create Date', auto_now_add=True)
    modify_date = models.DateTimeField('Modify Date', auto_now=True)

    class Meta:
        verbose_name = 'post'
        verbose_name_plural = 'posts'
        db_table ='my_post'
        ordering = ('-modify_date',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=(self.slug,))

    def get_previous_post(self):
        return self.get_previous_by_modify_date()

    def get_next_post(self):
        return self.get_next_by_modify_date()

# Create your models here.

site/photo/models.py
from __future__ import unicode_literals
from django.utils.encoding import python_2_unicode_compatible
from django.db import models
from django.core.urlresolvers import reverse
from photo.fields import ThumbnailImageField

@python_2_unicode_compatible
class Album(models.Model):
    name = models.CharField(max_length=50)
    description = models.CharField('One Line Description', max_length=100, blank=True)

    class Meta:
        ordering =['name']

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('photo:album_detail', args=(self.id,))

@python_2_unicode_compatible
class Photo(models.Model):
    album = models.ForeignKey(Album)
    title = models.CharField(max_length=50)
    image = ThumbnailImageField(upload_to='photo/%Y/%m')
    description = models.TextField('Photo Description', blank=True)
    upload_date = models.DateTimeField('Upload Date', auto_now_add=True)

    class Meta:
        ordering = ['title']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('photo:photo_detail', args =(self.id,))
# Create your models here.

site/blog/views.py
from django.views.generic import ListView, DetailView
from django.views.generic.dates import ArchiveIndexView, YearArchiveView, MonthArchiveView
from django.views.generic.dates import DayArchiveView, TodayArchiveView

from blog.models import Post

class PostLV(ListView):
    model = Post
    template_name = 'blog/post_all.html'
    context_object_name = 'posts'
    paginate_by = 2

class PostDV(DetailView):
    model = Post

class PostAV(ArchiveIndexView):
    model = Post
    date_field = 'modify_date'

class PostYAV(YearArchiveView):
    model = Post
    date_field = 'modify_date'
    make_object_list = True

class PostMAV(MonthArchiveView):
    model = Post
    date_field = 'modify_date'

class PostDAV(DayArchiveView):
    model = Post
    date_field = 'modify_date'

class PostTAV(TodayArchiveView):
    model = Post
    date_field = 'modify_date'
# Create your views here.

site/mysite/views.py
from django.views.generic.base import TemplateView

class HomeView(TemplateView):
    template_name = 'home.html'

site/photo/views.py
from django.views.generic import ListView, DetailView
from photo.models import Album, Photo

class AlbumLV(ListView):
    model = Album

class AlbumDV(DetailView):
    model = Album

class PhotoDV(DetailView):
    model = Photo
# Create your views here.

site/blog/templates/blog/post_all.html
{% extends 'base.html' %}
{% block content %}
<div style="padding:10px;">
<article>
             <hgroup>
                <h2>게시판</h2>
		            <h3>자유로운 게시글을 올리시면 됩니다.</h3>
            </hgroup>
            <table class="table_list" summary="게시판" cellspacing="0">
            <thead>
            <tr>
              <th scope="col">제목</th>
              <th scope="col">작성자</th>
              <th scope="col">작성일</th>
            </tr>
          </thead>
          <tbody>
           {% for post in posts %}
           <tr>
             <td class="title">
               <a href='{{ post.get_absolute_url }}'>{{ post.title }} </a>
             </td>
             <td>{{post.description}}</td>
             <td class="num"> {{ post.modify_date|date:"N d, Y" }}</td>
           </tr>
           {% endfor %}
         </tbody>
       </table>
     </article>

           <br/>

           <div>
             <span>
               {% if page_obj.has_previous %}
               <a href="?%page={{ page_obj.previous_page_number }}">PreviousPage</a>
               {% endif %}

               Page {{page_obj.number }} of {{ page_obj.paginator.num_pages }}

               {% if page_obj.has_next %}
               <a href="?page={{ page_obj.next_page_number }}">NextPage</a>
               {% endif %}
             </span>
           </div>
</div>
{% endblock %}

site/blog/templates/blog/post_archive.html
{% extends 'base.html' %}
{% block content %}
<div style="padding:10px;">
        <article>
                <h2>Post Archives until {% now "N d, Y" %}</h2>
                <ul>
                  {% for date in date_list %}
                  <li style="display: inline;">
                    <a href="{% url 'blog:post_year_archive' date|date:'Y' %}">Year-{{ date|date:"Y"}}</a></li>
                    {% endfor %}
                </ul>
              <br/>

              <div>
                <ul>
                  {% for post in posts %}
                  <li>{{ post.modify_date|date:"Y-m-d" }}&nbsp;&nbsp;&nbsp;
                    <a href="{{ post.get_absolute_url }}"><strong>{{post.title }}</strong></a></li>
           {% endfor %}
         </ul>
       </div>
        </article>
</div>
{% endblock %}

site/blog/templates/blog/post_archive_day.html
{% extends 'base.html' %}
{% block content %}
<div style="padding:10px;">
        <article>
                <h2>Post Archives for {{ day|date:"N d, Y" }}</h2>

              <div>
                <ul>
                  {% for post in object_list %}
                  <li>{{ post.modify_date|date:"Y-m-d" }}&nbsp;&nbsp;&nbsp;
                    <a href="{{ post.get_absolute_url }}"><strong>{{post.title }}</strong></a></li>
           {% endfor %}
         </ul>
       </div>
        </article>
      </div>

{% endblock %}

site/blog/templates/blog/post_archive_month.html
{% extends 'base.html' %}
{% block content %}
<div style="padding:10px;">
        <article>
                <h2>Post Archives for {{ month|date:"N, Y" }}</h2>

              <div>
                <ul>
                  {% for post in object_list %}
                  <li>{{ post.modify_date|date:"Y-m-d" }}&nbsp;&nbsp;&nbsp;
                    <a href="{{ post.get_absolute_url }}"><strong>{{post.title }}</strong></a></li>
           {% endfor %}
         </ul>
       </div>
        </article>
</div>
{% endblock %}

site/blog/templates/blog/post_archive_year.html
{% extends 'base.html' %}
{% block content %}
<div style="padding:10px;">
        <article>
                <h2>Post Archives for {{ year|date:"Y" }}</h2>

                <ul>
                  {% for date in date_list %}
                  <li style="display: inline;">
                    <a href="{% url 'blog:post_month_archive' year|date:'Y' date|date:'b' %}">{{ date|date:"F"}}</a></li>
                    {% endfor %}
                </ul>
              <br/>

              <div>
                <ul>
                  {% for post in object_list %}
                  <li>{{ post.modify_date|date:"Y-m-d" }}&nbsp;&nbsp;&nbsp;
                    <a href="{{ post.get_absolute_url }}"><strong>{{post.title }}</strong></a></li>
           {% endfor %}
         </ul>
       </div>
        </article>
</div>
{% endblock %}

site/blog/templates/blog/post_detail.html
{% extends 'base.html' %}
{% block content %}
<div style="padding:10px;">
        <article>
           <h2>제목: {{object.title}}</h2>

            <p>날짜: {{object.modify_date|date:"j F Y"}}</p>
            <br/>

            <div>
              {{object.content|linebreaks}}
            </div>
        </article>

        <p> {% if object.get_previous_by_modify_date %}
          <a href="{{ object.get_previous_post.get_absolute_url}}" title="View previous post"> &laquo;--{{ object.get_previous_post }}</a>
          {% endif %}

           {% if object.get_next_by_modify_date %}
           | <a href="{{ object.get_next_post.get_absolute_url}}" title="View next post"> {{ object.get_next_post }}--&raquo;</a>
           {% endif %}
         </p>
         <br/>
         <div>
           {% load disqus_tags %}
           {% disqus_show_comments %}
         </div>
       </div>
{% endblock %}

site/photo/templates/photo/album_detail.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block extrastyle %}{% static "photo/photo.css" %}{% endblock %}
{% block content %}
<div style="padding:20px;">
        <article>
          <h2>자료실</h2>
          <h3>사진을 게시하는 공간입니다.</h3>

           <p style="display:inline" >{{ object.name }}</p>
           &emsp;<small>{{ object.description }}</small>

         <hr/>

         <div class="album-detail" style="padding:15px;">
           {% for photo in object.photo_set.all %}
           <div class="album-detail-photo" style="float:left; margin-right:18px;">
             <a href="{{ photo.get_absolute_url }}">
               <img class="thumbnail" src="{{ photo.image.thumb_url }}"/>
             </a>
             <li>{{ photo.title }}</li>
             <li>{{ photo.upload_date|date:"Y-m-d" }}</li>
           </div>
           {% endfor %}
         </div>
       </div>


{% endblock %}

site/photo/templates/photo/album_list.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block extrastyle %}{% static "photo/photo.css" %}{% endblock %}
{% block content %}
<hgroup style="margin:10px;">

          <h2>자료실</h2>
          <h3>앨범명을 클릭하면 더 많은 사진을 볼 수 있습니다.</h3>
</hgroup>

          {% for item in object_list %}
          <div class="clear_float">
           <p style="display:inline; padding:10px;" ><a href="{% url 'photo:album_detail' item.id %}"> Album: {{ item.name }}</a></p>
           &emsp;<small>{{ item.description }}</small>
         </div>

         <hr/>

         <div class="album-list">
           {% for photo in item.photo_set.all|slice:":5" %}
           <div class="album-list-photo" style="float:left; margin-right:3px; margin-bottom:30px;">
             <a href="{{ photo.get_absolute_url }}">
               <img class="thumbnail" src="{{ photo.image.thumb_url }}"/>
             </a>
           </div>
           {% endfor %}
         </div>

         {% endfor %}

{% endblock %}

site/photo/templates/photo/photo_detail.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block extrastyle %}{% static "photo/photo.css" %}{% endblock %}
{% block content %}
<div style="padding:10px;">
        <article>
          <h2>{{ object.title }}</h2>
          <table class="photo_detail">
            <tr>
              <td>
                <a href="{{ object.image.url }}">
                  <img style="max-width:100%" src="{{ object.image.url }}" />
                </a>
              </td>

              <td>
                <ul>
                  <li>Photo Description</li>
                  {% if object.description %}<p>{{ object.description|linebreaks }}</p>
                  {% else %}<p>(blank)</p>{% endif %}
                  <li>Date Uploaded</li>
                  <p>{{ object.upload_date }}</p>
                  <li>Album Name</li>
                  <p><a href="{% url 'photo:album_detail' object.album.id %}">{{ object.album.name }}</a></p>
                </ul>
              </td>
            </tr></table>
          </div>

{% endblock %}

site/templates/base.html
<!doctype html>
<html lang="ko">
  <head>
    <title>Quipu Layout</title>
    <style>
        header, section, footer, aside, nav, article, figure, figcaption{ dispaly: block;}
	body{
	color:#666666;
        background-color: #f9f8f6;
        background-position: center;
        font-family: "Gill Sans", Arial, sans-serif;
        line-height: 1.4em;
        margin: 0px;
        font-size: 15px;
	}
        .wrapper{
            width: 940px;
            margin: 20px auto 20px auto;
            border: 2px solid #000000;
            background-color: #ffffff;
        }
      header {
        height: 160px;
        background-color:#ffcccc;
      }
      h1{
          color:#ffffff;
          text-shadow:-1px -1px #111111;
          font-size: 400%;
          width: 940px;
          height: 130px;
          margin: 0px;
      }
      nav,footer{
          clear: both;
          color: #ffffff;
          background-color:  #aeaca8;
          height: 30px;
      }
      nav ul{
          margin:0px;
          padding: 5px 0px 5px 30px;
      }
      nav li{
          display: inline;
          margin-right:40px;
      }
      nav li a{
          color: #ffffff;
      }
      nav li a:hover, nav li a.current{
          color:#000000;
      }
      section.courses{
          float: left;
          width: 659px;
          border-right: 1px solid #eeeeee;
      }
      article{
          clear: both;
          overflow:auto;
          width:100%;
      }
      hgroup{
          margin-top:40px;
      }
      figure{
          float:left;
          width:290px;
          height:220px;
          padding:5px;
          margin:20px;
          border:1px solid #eeeeee;
      }
      figcaption{
          font-size:90%;
          text-align: left;
      }
      aside{
          width:230px;
          float:left;
          padding: 0px 0px 0px 20px;
      }
      aside section a{
          display: block;
          padding: 10px;
          border-bottom: 1px solid #eeeeee;
      }
      aside section a:hover{
          color: #985d6a;
          background-color: #efefef;
      }
      a{
          color: #FF7E9D;
          text-decoration: none;
      }
      h1,h2,h3{
          font-weight: normal;
      }
      h2{
          margin: 10px 0px 5px 0px;
          padding: 0px;
      }
      h3{
          margin: 0px 0px 10px 0px;
          color:#de6581;

      }
      hr{
        color: #aeaca8;
      }
      .table_list{
        width: 100%;
        font-size: 12px;
      }
      .table_list thead tr th {
        height: 35px;
        background: #494949;
        color: #fff;
        font-weight: bold;
      }
      .table_list tbody tr td {
        line-height: 35px;
        border-bottom:1px solid #c3c3c3;
        text-align: center;
      }
      .table_list tbody tr td.num{
        font-family: Tahoma;
        font-size: 11px;
        color: #737373;
      }
      .table_list tbody tr td.title{
        text-align: left;
      }
      .table_list tbody tr td.title a{
        display:block;
        float:left;
        text-decoration: none;
        color: #191919;
        max-width: 320px;
        white-space: nowrap;
        overflow: hidden;
        text-overflow: ellipsis;
      }
      .table_list tbody tr td.title a:hover{
        text-decoration: underline;
      }
      aside h2{
          padding: 30px 0px 10px 0px;
          color: #de6581;
      }
      footer{
          font-size:80%;
          padding: 7px 0px 0px 20px;
      }

    </style>
    <!--[ifit IE9]>
    <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
  </head>
  <body>
    <div class="wrapper">
      <header>
          <h1><br/><br/><br/><a href="{% url 'home' %}"> QUIPU WEBSITE </a></h1>
        <nav>
            <ul>
                <li><a href="{% url 'home' %}" class="current">홈</a></li>
                <li><a href="" >공지사항</a></li>
                <li><a href="" >활동</a></li>
                <li><a href="{% url 'blog:index' %}" >게시판</a></li>
                <li><a href="{% url 'photo:index' %}" >자료실</a></li>
                <li><a href="{% url 'blog:post_archive' %}" >Archive</a></li>
                <li><a href="" >Search</a></li>
            </ul>
        </nav>
      </header>

      <section class="courses">
      {% block content %}
      {% endblock %}
      </section>
	<aside>
           <section class="school">
	         <h2>학교 홈페이지</h2>
		<a href="https://www.uos.ac.kr/main.do">서울시립대 메인사이트</a>
		<a href="https://portal.uos.ac.kr/user/login.face">서울시립대 포털사이트</a>
		<a href="http://cafe338.daum.net/_c21_/home?grpid=1k4k">서울시립대 광장</a>
		<a href="http://uos.fbpage.kr/#/search">서울시립대 대나무숲</a>
	</section>
	<section class="contact">
	         <h2>연락처</h2>
		<p>회장 김종현<br/>
		010-6478-9865 <br/><br/>
		부회장 임동영<br/>
		010-9169-7157</p>

	</section>
	</aside>
	<footer>
	모든 제작권은 ooo에게 있음
	</footer>
	</div><!-- .wrapper -->
</body>
</html>

site/templates/home.html
{% extends 'base.html' %}
{% block content %}
        <article>
            <figure>
                <img src="http://ppss.kr/wp-content/uploads/2016/01/CodingSnippet.jpg" alt="computer" style="width:290px; height:180px;"/>
                <figcaption>Bae YuBin</figcaption>
            </figure>
            <hgroup>
                <h2>UOS 중앙동아리 Quipu</h2>
		<h3>퀴푸홈페이지에 오신걸 환영합니다.</h3>
            </hgroup>
		<p>
		저희는 주로 안드로이드와같은 프로그래밍 언어를 공부하지만<br/>
        	의무사항이 아니기 때문에<br/>
                전공자, 비전공자 모두에게 열려있습니다.<br/>
		오셔서 같이 공부도 하고 보드게임도 해요~<br/></p>
        </article>

	 <article>
            <figure>
                <img src="http://cfile7.uf.tistory.com/image/263BC53858878964015141" alt="computer" style="width:290px; height:180px;"/>
                <figcaption>Bae YuBin</figcaption>
            </figure>
            <hgroup>
                <h2>Quipu 동아리 활동</h2>
		<h3>전공 관련 자체 강의및 프로젝트 진행</h3>
            </hgroup>
		<p>학부생의 전공과목 학습에 도움이 되고자 <br/>자체적인 강의를 진행하고있습니다.<br/>
        	그밖에도 게임제작, 아두이노, 라즈베리 파이등<br/>
		다양한 프로젝트를 진행하고 있습니다.<br/></p>
        </article>
{% endblock %}